name: flexi_storage
description: "A lightweight and flexible key-value storage solution for Dart and Flutter, supporting encryption, caching, and batch operations."
version: 1.0.1+2
repository: https://github.com/BrennerFerreira/flexi_storage
issue_tracker: https://github.com/BrennerFerreira/flexi_storage/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.6
  encrypt: ^5.0.3
  universal_web: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  path_provider: ^2.1.5

flutter:

tags:
  - storage
  - key-value
  - encryption
  - caching
  - flutter
  - dart
  - batch-operations
  - lightweight
  - cross-platform

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
